const personajes = {

    Brenda: {

        nombre: "Brenda",

        descripcion: "Brenda es una personaje de la historia.",

        imagen:
        "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg"

    },


    Bradly: {

        nombre: "Bradly",

        descripcion: "Bradly es otro personaje de la historia.",

        imagen:
        "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg"

    },


    Kyoto: {

        nombre: "Kyoto",

        descripcion: "Kyoto es una personaje de la historia.",

        imagen:
        "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg"

    },

    Richard: {

        nombre: "Richard",

        descripcion: "Richard es un personaje de la historia.",

        imagen:
        "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg"

    },


}
